<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=0.45, minimum-scale=0.45">

        <title>SaFraffle</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css2?family=Dosis&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Berkshire+Swash&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Josefin+Slab:wght@700&display=swap" rel="stylesheet">

        <!-- Styles -->
        <style>
            @media screen and (min-width: 500px) {
              img {
                width: auto;
              }
	      .center {
                width: auto;
              }
	      img.footer {
                width: 100px;
              }
            }
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Dosis', sans-serif;
                font-weight: 200;
                margin: 0;
            } 
            img {
              width:800px;
	      margin: auto;
            }
            img.footer {
              width:400px;
	      margin: auto;
              display: block;
            }
	    .center {
              display: block;
              width: 800px;
	      margin: auto;
              align-items: center;
              justify-content: center;
            }
	    p {
              padding: 0em 15px 0em;
	    }
	    p.list {
              margin: 0px auto 1px;
            }
            .content {
                text-align: center;
            }

            .title {
                font-size: 50px;
		font-family: 'Berkshire Swash', cursive;
            }
            .subtitle {
              font-family: 'Josefin Slab', serif;
            } 
        </style>
    </head>
    <body>
        <div class="center">
	<img src="https://www.safraffle.com/storage/img/Safraffle_TopBanner.png">
        <div class="center">

            <div class="content">
                <div class="title ">
		  Safraffle Raffle: #BlackTransLivesMatter
                </div>
<p class="subtitle">September 11th through September 27th</p>
<p class="subtitle">This web-app will go live starting 7 AM September 11th 2020</p>
<p class="subtitle">You will be able to purchase tickets through this web-app and at Safai Coffee Shop at 1707 Bardstown Road!</p>
<p class="subtitle">Tickets are $5 each or 5 tickets for $20!</p>

<p>This raffle will benefit Change Today, Change Tomorrow's Black Trans Lives Matter Campaign. The funds generated by this campaign will be used to provide Black Trans, Gender Non-Conforming, and Non-Binary individuals in Louisville, KY with medical supplies, mental health services, medical services, and empowerment. CTCT has a matching campaign goal of $15,000 but they're not there yet! By participating in this first Safraffle Raffle you will have a chance to not only win some cool prizes from local businesses but also assist CTCT in reaching their goal and help a marginalized group receive health care and services they desperately need, especially in these turbulent times.</p>

<p class="list">Raffle Items proudly donated by:</p>
<p class="list">Bourbon Barrel Foods</p>
<p class="list">Fleur de Lou</p>
<p class="list">Home Skate Shop</p>
<p class="list">Jeeka Does It</p>
<p class="list">Louisville Cream </p>
<p class="list">LouVino</p>
<p class="list">Safai Coffee Shop</p>

<p>If you have any questions please call Safai Coffee Shop at 502-384-3555</p>

            </div>
        </div>
	<img class="footer" src="https://www.safraffle.com/storage/img/Safai_CTCT_logos.png">
        </div>
    </body>
</html>
